version: '3.3'

services:
  php-cli:
    container_name: rem_it_bot_php
    profiles: ["main", "dev"]
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ${BACKUPS_FOLDER}:/backup
    depends_on:
      - composer
    networks:
      - rib_network

  composer:
    container_name: rem_it_bot_composer
    profiles: ["main", "dev"]
    image: composer
    volumes:
      - ./app:/app
    working_dir: /app
    command: install
    networks:
      - rib_network

  mysql:
    container_name: rem_it_bot_mysql
    profiles: ["main", "dev"]
    image: mysql
    restart: unless-stopped
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - rib_network


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    profiles: ["dev"]
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=${MYSQL_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql
    networks:
      - rib_network

networks:
  rib_network:
    driver: bridge