version: '3.3'

services:
  php-cli:
    container_name: rem_it_bot_php
#    profiles: ["main"]
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    depends_on:
      - composer

  composer:
    container_name: rem_it_bot_composer
#    profiles: ["main"]
    image: composer
    volumes:
      - ./app:/app
    working_dir: /app
    command: install

  mysql:
    container_name: rem_it_bot_mysql
#    profiles: ["main"]
    image: mysql
    restart: unless-stopped
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
##    profiles: ["debug"]
#    ports:
#      - "8080:80"
#    environment:
#      - PMA_HOST=${MYSQL_HOST}
#      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#    depends_on:
#      - mysql